export const config = {
  settings: {
    goalSoft: 1_000_000,
    milestone: 25,
    milestoneMul: 2,
    intervalMul: 0.85,
    nextCarCooldownMinutes: 0.5,
    rngSeed: 12345,
    emojiFallback: "🚗",
    collectionBoostPerSalePct: 5,
    carBaseCost: 40000,
    carCostFactor: 4.2
  },
  rarities: {
    common:    { dropChance: 0.40, unlockCostGems: 1 },
    uncommon:  { dropChance: 0.30, unlockCostGems: 2 },
    rare:      { dropChance: 0.20, unlockCostGems: 4 },
    epic:      { dropChance: 0.09, unlockCostGems: 7 },
    legendary: { dropChance: 0.01, unlockCostGems: 12 }
  },
  cars: [
    { id:"car_apex_bolt", name:"Apex Bolt", file:"transport_stat_donate_1.png", rarity:"rare", tags:["sport","turbo","aero","track"], boost:{activePct:40, passivePerSec:10}, locked:false },
    { id:"car_midnight_hauler", name:"Midnight Hauler", file:"transport_stat_donate_2.png", rarity:"uncommon", tags:["diesel","utility","offroad"], boost:{activePct:0, passivePerSec:15}, locked:false },
    { id:"car_cerulean_sprinter", name:"Cerulean Sprinter", file:"transport_stat_donate_3.png", rarity:"rare", tags:["sport","tuner","neon","compact"], boost:{activePct:25, passivePerSec:0}, locked:false },
    { id:"car_ironclad_scout", name:"Ironclad Scout", file:"transport_stat_modifier_1.png", rarity:"common", tags:["offroad","rugged","diesel"], boost:{activePct:0, passivePerSec:10}, locked:false },
    { id:"car_solar_pulse", name:"Solar Pulse", file:"transport_stat_modifier_1_1.png", rarity:"rare", tags:["electric","compact","aero","futuristic"], boost:{activePct:0, passivePerSec:20}, locked:false },
    { id:"car_crimson_drift", name:"Crimson Drift", file:"transport_stat_modifier_2.png", rarity:"rare", tags:["tuner","drift","sport","neon"], boost:{activePct:30, passivePerSec:0}, locked:false },
    { id:"car_alpine_trail", name:"Alpine Trail", file:"transport_stat_modifier_2_1.png", rarity:"uncommon", tags:["offroad","turbo","sport"], boost:{activePct:10, passivePerSec:10}, locked:false },
    { id:"car_velvet_royale", name:"Velvet Royale", file:"transport_stat_modifier_3.png", rarity:"epic", tags:["luxury","comfort","touring","leather"], boost:{activePct:0, passivePerSec:35}, locked:false },
    { id:"car_stealth_phantom", name:"Stealth Phantom", file:"transport_stat_modifier_3_1.png", rarity:"epic", tags:["stealth","aero","exotic","carbon"], boost:{activePct:35, passivePerSec:0}, locked:false },
    { id:"car_thunder_wagon", name:"Thunder Wagon", file:"transport_stat_modifier_4.png", rarity:"uncommon", tags:["muscle","turbo","diesel"], boost:{activePct:20, passivePerSec:5}, locked:false },
    { id:"car_copper_runner", name:"Copper Runner", file:"transport_stat_modifier_1_2.png", rarity:"common", tags:["compact","utility"], boost:{activePct:0, passivePerSec:8}, locked:false },
    { id:"car_azure_courier", name:"Azure Courier", file:"transport_stat_modifier_1_3.png", rarity:"uncommon", tags:["utility","aero","compact"], boost:{activePct:5, passivePerSec:12}, locked:false },
    { id:"car_stormliner", name:"Stormliner", file:"transport_stat_modifier_4_1.png", rarity:"epic", tags:["aero","luxury","touring","carbon"], boost:{activePct:15, passivePerSec:25}, locked:false },
    { id:"car_blaze_pickup", name:"Blaze Pickup", file:"transport_stat_modifier_5.png", rarity:"uncommon", tags:["utility","muscle","offroad"], boost:{activePct:18, passivePerSec:0}, locked:false },
    { id:"car_forge_titan", name:"Forge Titan", file:"transport_stat_modifier_5_1.png", rarity:"rare", tags:["rugged","diesel","muscle","offroad"], boost:{activePct:20, passivePerSec:10}, locked:false },
    { id:"car_glacier_trek", name:"Glacier Trek", file:"transport_stat_modifier_6.png", rarity:"rare", tags:["offroad","comfort","touring","rugged"], boost:{activePct:0, passivePerSec:25}, locked:true },
    { id:"car_helix_runner", name:"Helix Runner", file:"transport_stat_modifier_6_1.png", rarity:"rare", tags:["aero","tuner","sport","compact"], boost:{activePct:28, passivePerSec:0}, locked:true },
    { id:"car_obsidian_crawler", name:"Obsidian Crawler", file:"transport_stat_modifier_7.png", rarity:"epic", tags:["stealth","offroad","rugged","carbon"], boost:{activePct:22, passivePerSec:18}, locked:true },
    { id:"car_vortex_arrow", name:"Vortex Arrow", file:"transport_stat_modifier_7_1.png", rarity:"epic", tags:["aero","turbo","exotic","sport"], boost:{activePct:40, passivePerSec:0}, locked:true },
    { id:"car_pulse_city", name:"Pulse City", file:"transport_stat_modifier_8.png", rarity:"uncommon", tags:["compact","neon","utility"], boost:{activePct:0, passivePerSec:12}, locked:true },
    { id:"car_crystal_glide", name:"Crystal Glide", file:"transport_stat_modifier_8_1.png", rarity:"rare", tags:["luxury","comfort","aero","electric"], boost:{activePct:0, passivePerSec:28}, locked:true },
    { id:"car_shadow_warden", name:"Shadow Warden", file:"transport_stat_modifier_9.png", rarity:"epic", tags:["stealth","muscle","carbon","tuner"], boost:{activePct:35, passivePerSec:0}, locked:true },
    { id:"car_nova_sprint", name:"Nova Sprint", file:"transport_stat_modifier_9_1.png", rarity:"rare", tags:["turbo","aero","compact","sport"], boost:{activePct:30, passivePerSec:0}, locked:true },
    { id:"car_titan_haul", name:"Titan Haul", file:"transport_stat_modifier_10.png", rarity:"common", tags:["utility","diesel","rugged"], boost:{activePct:0, passivePerSec:10}, locked:true },
    { id:"car_chrome_lance", name:"Chrome Lance", file:"transport_stat_modifier_10_1.png", rarity:"rare", tags:["aero","exotic","track","carbon"], boost:{activePct:32, passivePerSec:0}, locked:true },
    { id:"car_eclipse_royale", name:"Eclipse Royale", file:"transport_stat_modifier_11.png", rarity:"legendary", tags:["luxury","exotic","carbon","touring","stealth"], boost:{activePct:0, passivePerSec:45}, locked:true },
    { id:"car_aurora_drift", name:"Aurora Drift", file:"transport_stat_modifier_12.png", rarity:"epic", tags:["drift","neon","tuner","sport"], boost:{activePct:38, passivePerSec:0}, locked:true },
    { id:"car_maglev_whisper", name:"Maglev Whisper", file:"transport_stat_modifier_13.png", rarity:"legendary", tags:["electric","futuristic","aero","comfort","luxury"], boost:{activePct:0, passivePerSec:50}, locked:true },
    { id:"car_howl_charger", name:"Howl Charger", file:"transport_stat_modifier_14.png", rarity:"epic", tags:["muscle","turbo","track","sport"], boost:{activePct:42, passivePerSec:0}, locked:true },
    { id:"car_zenith_pulse", name:"Zenith Pulse", file:"transport_stat_modifier_15.png", rarity:"legendary", tags:["electric","futuristic","exotic","carbon","aero"], boost:{activePct:45, passivePerSec:10}, locked:true }
  ],
  collections: [
    { id:"track_kings",   name:"Track Kings",   tags:["sport","aero","track"], rewardFirst:5, rewardRepeat:1, bonus:{activePct:5} },
    { id:"street_neon",   name:"Street Neon",   tags:["tuner","drift","neon"], rewardFirst:5, rewardRepeat:1, bonus:{passivePct:5} },
    { id:"heavy_duty",    name:"Heavy Duty",    tags:["diesel","utility","rugged"], rewardFirst:5, rewardRepeat:1, bonus:{tickPct:-5} },
    { id:"green_pulse",   name:"Green Pulse",   tags:["electric","futuristic","compact"], rewardFirst:5, rewardRepeat:1, bonus:{carCostPct:-5} },
    { id:"grand_tour",    name:"Grand Tour",    tags:["luxury","comfort","touring","leather"], rewardFirst:5, rewardRepeat:1, bonus:{passivePct:7} },
    { id:"silent_strike", name:"Silent Strike", tags:["stealth","exotic","carbon"], rewardFirst:5, rewardRepeat:1, bonus:{activePct:7} },
    { id:"boost_brigade", name:"Boost Brigade", tags:["turbo","muscle","offroad"], rewardFirst:5, rewardRepeat:1, bonus:{tickPct:-7} },
    { id:"city_micro",    name:"City Micro",    tags:["compact","utility","aero"], rewardFirst:5, rewardRepeat:1, bonus:{carCostPct:-7} },
    { id:"night_run",     name:"Night Run",     tags:["neon","stealth","sport"], rewardFirst:5, rewardRepeat:1, bonus:{activePct:6, passivePct:6} },
    { id:"full_garage",   name:"Full Garage",   tags:"ALL", rewardFirst:5, rewardRepeat:1, bonus:{activePct:10, passivePct:10, tickPct:-10, carCostPct:-10} }
  ],
  generators: [
    { id:"g1",  icon:"🛠️", name:"Tool Bench",    active:0.8,  passive:0.6, baseCost:20,    growth:1.11, interval:1.2 },
    { id:"g2",  icon:"🔧", name:"Starter Motor",  active:1.2,  passive:1.4, baseCost:70,    growth:1.12, interval:1.8 },
    { id:"g3",  icon:"⚙️", name:"Gear Press",    active:2.5,  passive:2.0, baseCost:180,   growth:1.13, interval:2.5 },
    { id:"g4",  icon:"🪛", name:"Panel Shop",    active:1.8,  passive:4.2, baseCost:420,   growth:1.14, interval:3.1 },
    { id:"g5",  icon:"🧰", name:"Body Line",     active:4.5,  passive:3.8, baseCost:900,   growth:1.15, interval:3.8 },
    { id:"g6",  icon:"🚧", name:"Chassis Jig",   active:3.2,  passive:7.5, baseCost:2000,  growth:1.16, interval:4.6 },
    { id:"g7",  icon:"🏭", name:"Paint Booth",   active:8.5,  passive:6.5, baseCost:4500,  growth:1.17, interval:5.4 },
    { id:"g8",  icon:"🚚", name:"Test Track",    active:6.0,  passive:11.5,baseCost:10000, growth:1.18, interval:6.2 },
    { id:"g9",  icon:"⚡", name:"Dyno Cell",     active:14.0, passive:9.0, baseCost:22000, growth:1.19, interval:7.1 },
    { id:"g10", icon:"🚀", name:"Launch Bay",   active:10.0, passive:18.0,baseCost:48000, growth:1.2,  interval:8.3 }
  ]
};
